(function() {var implementors = {};
implementors["cookie"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"cookie/struct.CookieBuilder.html\" title=\"struct cookie::CookieBuilder\">CookieBuilder</a>",synthetic:true,types:["cookie::builder::CookieBuilder"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"cookie/struct.CookieJar.html\" title=\"struct cookie::CookieJar\">CookieJar</a>",synthetic:true,types:["cookie::jar::CookieJar"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"cookie/struct.Delta.html\" title=\"struct cookie::Delta\">Delta</a>&lt;'a&gt;",synthetic:true,types:["cookie::jar::Delta"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"cookie/struct.Iter.html\" title=\"struct cookie::Iter\">Iter</a>&lt;'a&gt;",synthetic:true,types:["cookie::jar::Iter"]},{text:"impl&lt;'c&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"cookie/struct.Cookie.html\" title=\"struct cookie::Cookie\">Cookie</a>&lt;'c&gt;",synthetic:true,types:["cookie::Cookie"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"cookie/enum.ParseError.html\" title=\"enum cookie::ParseError\">ParseError</a>",synthetic:true,types:["cookie::parse::ParseError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"cookie/enum.SameSite.html\" title=\"enum cookie::SameSite\">SameSite</a>",synthetic:true,types:["cookie::draft::SameSite"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
